"""empty message

Revision ID: f3aab3cb10a3
Revises: 
Create Date: 2022-02-23 20:49:26.845248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3aab3cb10a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('add_ons', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drinks', sa.Column('selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drinks', 'selected')
    op.drop_table('order')
    # ### end Alembic commands ###
